# 40 quarters = 10 years
STATEMENT_QUARTERLY_LIMIT = 40
STATEMENT_YEARLY_LIMIT = 10

# ICB CODE OF INDUSTRY THAT PROVIDE DIRECT CASHFLOW STATEMENT IN FORM OF TWO DIGITS
CASHFLOW_DIRECT_ICB_CODES = [83, 85, 87]
CF_DIRECT_ICB_BLACKLIST = [8781]